server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: admin
    url: jdbc:postgresql://ec2-54-228-32-29.eu-west-1.compute.amazonaws.com/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: host
    port: port
    username: agricocommerce
    password: jcemdwbymjiekhfh

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000